export type NavLink = { href: string; label: string };
export type NavGroup = { label: string; href: string; children: NavLink[] };

export const navGroups: NavGroup[] = [
  {
    label: "About",
    href: "/about",
    children: [
      { href: "/about", label: "About Helum" },
      { href: "/vision-mission", label: "Vision & Mission" },
      { href: "/values", label: "Our Values" },
      { href: "/why-helum", label: "Why Helum" },
      { href: "/about/approach", label: "Our Approach" },
      { href: "/about/story", label: "Our Story" },
    ],
  },
  {
    label: "Services",
    href: "/services",
    children: [
      { href: "/services/renewable-energy", label: "Renewable Energy" },
      { href: "/services/solar-pv", label: "Solar PV Systems" },
      { href: "/services/battery-storage", label: "Battery Storage" },
      { href: "/services/backup-power", label: "Backup Power" },
      { href: "/services/off-grid", label: "Off-Grid Energy" },
      { href: "/services/energy-power-technology", label: "Energy & Power Technology" },
      { href: "/services/productive-use", label: "Productive-Use Technology" },
      { href: "/services/strategic-partnerships", label: "Strategic Partnerships" },
    ],
  },
  {
    label: "Products",
    href: "/products",
    children: [
      { href: "/products", label: "All Products" },
      { href: "/products/inverters", label: "Inverters" },
      { href: "/products/lithium-batteries", label: "Lithium Batteries" },
      { href: "/products/power-stations", label: "Power Stations" },
      { href: "/products/solar-panels", label: "Solar Panels" },
      { href: "/products/solar-water-pumps", label: "Solar Water Pumps" },
    ],
  },
  {
    label: "Solutions",
    href: "/solutions",
    children: [
      { href: "/solutions/homes", label: "Homes" },
      { href: "/solutions/businesses", label: "Businesses" },
      { href: "/solutions/institutions", label: "Institutions" },
      { href: "/solutions/agriculture", label: "Agriculture" },
      { href: "/solutions/water-irrigation", label: "Water & Irrigation" },
      { href: "/solutions/food-processing", label: "Food Processing & Cold Chain" },
      { href: "/solutions/smes-rural", label: "SMEs & Rural Enterprises" },
    ],
  },
  {
    label: "Technology & Partnerships",
    href: "/technology",
    children: [
      { href: "/technology/sourcing", label: "Technology Sourcing" },
      { href: "/technology/market-access", label: "Market Access" },
      { href: "/partnerships", label: "Technology Partnerships" },
      { href: "/opportunity", label: "Investment Opportunities" },
      { href: "/technology/partner", label: "Partner With Helum" },
    ],
  },
  {
    label: "Process",
    href: "/process",
    children: [
      { href: "/process", label: "Our Process" },
      { href: "/engineering/installation", label: "Engineering & Installation" },
      { href: "/engineering/maintenance", label: "Maintenance & Support" },
    ],
  },
  {
    label: "Contact",
    href: "/contact",
    children: [
      { href: "/contact", label: "Contact Us" },
      { href: "/contact/consultation", label: "Request a Consultation" },
      { href: "/faq", label: "FAQs" },
    ],
  },
];

export const allRoutes = [
  "/",
  "/about",
  "/vision-mission",
  "/values",
  "/why-helum",
  "/about/approach",
  "/about/story",
  "/services",
  "/services/renewable-energy",
  "/services/solar-pv",
  "/services/battery-storage",
  "/services/backup-power",
  "/services/off-grid",
  "/services/energy-power-technology",
  "/services/productive-use",
  "/services/strategic-partnerships",
  "/products",
  "/products/inverters",
  "/products/lithium-batteries",
  "/products/power-stations",
  "/products/solar-panels",
  "/products/solar-water-pumps",
  "/solutions",
  "/solutions/homes",
  "/solutions/businesses",
  "/solutions/institutions",
  "/solutions/agriculture",
  "/solutions/water-irrigation",
  "/solutions/food-processing",
  "/solutions/smes-rural",
  "/who-we-serve",
  "/technology",
  "/technology/sourcing",
  "/technology/market-access",
  "/partnerships",
  "/opportunity",
  "/technology/partner",
  "/process",
  "/engineering/installation",
  "/engineering/maintenance",
  "/contact",
  "/contact/consultation",
  "/faq",
  "/privacy",
  "/terms",
];
